from tkinter import *
import pyttsx3
import speech_recognition as sr
import webbrowser
import playsound
from googletrans import Translator
from gtts import gTTS
import os
import datetime
import PIL.Image, PIL.ImageTk
from PIL import Image
import cv2
import json
import requests
import sys

window = Tk()

var = StringVar()
var1 = StringVar()


translator = Translator(service_urls=[
      'translate.google.com',
      'translate.google.co.in',
    ]) 


num = 1

def assistantt_speaks(output):
    global num
    num += 1
    #print("Jarvis : ", output)
    toSpeak = gTTS(text = output, lang ='mr', slow = False) 
    file = str(num)+".mp3 "
    toSpeak.save(file)
    playsound.playsound(file, True)
    os.remove(file) 

def get_audios():
    Robject = sr.Recognizer()
    with sr.Microphone() as source:
        var.set("बोला...")
        window.update()
        print("बोला...")
        Robject.pause_threshold = 1
        Robject.energy_threshold = 400
        audio = Robject.listen(source)
    try:
        var.set("थांबा.")
        window.update()
        print("थांबा")
        text = Robject.recognize_google(audio, language='mr')
        print(text)
    except Exception as e:
        var.set("कृपया पुन्हा बोला...")
        window.update()
        assistantt_speaks("कृपया पुन्हा बोला...")
        return "None"
    var1.set(text)
    window.update()
    return text


def marplay():
    btn2.configure(bg = 'red')
    if __name__ == "__main__":
        hour = int(datetime.datetime.now().hour)
        if hour>=0 and hour<12:
            var.set('शुभ प्रभात')
            window.update()
            assistantt_speaks("शुभ प्रभात") 
            translations = translator.translate(['Good morning'], dest='mr')
            for translation in translations:
                print(translation.origin, ' -> ', translation.text)   
   
        elif hour>=12 and hour<18:
            var.set('शुभ दुपार')
            window.update()
            assistantt_speaks("शुभ दुपार")
            translations = translator.translate(['Good afternoon'], dest='mr')
            for translation in translations:
                print(translation.origin, ' -> ', translation.text)
        else:
            var.set('शुभ संध्या')
            window.update()
            assistantt_speaks("शुभ संध्या")
            translations = translator.translate(['Good Evening'], dest='mr')
            for translation in translations:
                print(translation.origin, ' -> ', translation.text)

        while(1):
            var.set('नमस्कार.')
            window.update()
            assistantt_speaks("नमस्कार.")
            assistantt_speaks('मी तुम्हाला कशी मदत करू शकते?')
            var.set('मी तुम्हाला कशी मदत करू शकते?')
            window.update()
            assistantt_speaks('मुख्यपृष्ठ बद्दल?')
            var.set('मुख्यपृष्ठ बद्दल?')
            window.update()
            assistantt_speaks(' किंवा जिल्ह्याविषयी ?')
            var.set('किंवा जिल्ह्याविषयी ?')
            window.update()
            assistantt_speaks('किंवा सावर्जनिक सुविधा  बद्दल  ?')
            var.set('किंवा सावर्जनिक सुविधा बद्दल?')
            window.update()
            assistantt_speaks('किंवा पर्यटन बद्दल ?')
            var.set('किंवा पर्यटन बद्दल?')
            window.update()
            assistantt_speaks('तुम्हाला काही सूचना फॉर्म भरायचा आहे का?')
            var.set('तुम्हाला काही सूचना फॉर्म भरायचा आहे का?')
            window.update()
            text = get_audios()

            

            if 'जिल्ह्याविषयी' in str(text):
                assistantt_speaks('तुम्हाला जिल्ह्याविषयी काय जाणून घ्यायचे आहे?')
                var.set('तुम्हाला जिल्ह्याविषयी काय जाणून घ्यायचे आहे?')
                window.update()
                assistantt_speaks('इतिहास')
                var.set('इतिहास')
                window.update()
                assistantt_speaks('जिल्ह्याचा नकाशा')
                var.set('जिल्ह्याचा नकाशा')
                window.update()
                assistantt_speaks('कोण कोण आहे')
                var.set('कोण कोण आहे')
                window.update()
                assistantt_speaks('लोकप्रतिनिधी')
                var.set('लोकप्रतिनिधी')
                window.update()
                texts = get_audios()

                            
                if 'इतिहास' in str(texts):
                    assistantt_speaks('इतिहास')
                    assistantt_speaks('रूपरेखा')
                    assistantt_speaks('सिंधुदुर्ग जिल्हा हा ५,२०७ चौ.किमी. क्षेत्रामध्ये पसरलेला आहे. या जिल्ह्याची लोकसंख्या २००१ च्या जनगणने प्रमाणे ८,६८,८२५ एवढी आहे. आधुनिकीकरण करण्यात आलेले सिंधुदुर्गनगरी हे शहर जिल्ह्याचे मुख्यालय आहे. सिंधुदुर्ग हा पूर्वेकडून अरबी समुद्राने, दक्षिणेकडून बेळगाव जिल्हा (कर्नाटक राज्य) आणि गोवा राज्याने तर उत्तरेकडून रत्नागिरी जिल्ह्याने वेढला गेलेला आहे. हा जिल्हा समुद्र किनारी असल्यामुळे येथील हवामान नेहमी उष्ण व दमट असते त्यामुळे तापमानावर बदलत्या ऋतूंचा फारसा परिणाम होत नाही. येथील कुडाळ,कणकवली व सावंतवाडी या प्रमुख शहरातून जाणारा राष्ट्रीय महामार्ग क्र. तसेच कणकवली, सिंधुदुर्गनगरी, कुडाळ, सावंतवाडी येथील रेल्वे स्थानकांवरून येथे पोचता येते. रत्नागिरी, बेळगाव (कर्नाटक) आणि दाभोली (गोवा) ही जवळील विमानतळे आहेत.')
                    assistantt_speaks('सिंधुदुर्ग जिल्ह्याचा संक्षिप्त इतिहास')
                    assistantt_speaks('सिंधुदुर्ग जिल्हा हा ‘कोकण’ या उंच पठारी प्रदेशाच्या पश्चिमेला असून ऐतिहासीक रीत्या आपल्या लांब तट रेखा आणि सुरक्षित बंदरे यांसाठी प्रसिद्ध आहे. हा जिल्हा पूर्वी रत्नागिरी जिल्ह्याचा एक भाग होता. परंतु  १ मे १९८१  पासून प्रशासकीय सुविधा तसेच औद्योगिक आणि कृषी विकास यांच्या साठी रत्नागिरी आणि सिंधुदुर्ग अशा २ जिल्ह्यात विभागीत करण्यात आला. सिंधुदुर्ग जिल्ह्यात सध्या सावंतवाडी, कुडाळ, वेंगुर्ला, मालवण, देवगड, कणकवली, वैभववाडी आणि दोडामार्ग अशा तहसील केंद्रांचा समावेश होतो. ‘कोंकण’ हा शब्द मुळ भारतीय व पुरातन असून या नावाची पुरेशी माहिती उपलब्ध नाही.')
                    assistantt_speaks('रत्नागिरी जिल्हा हा शिलाहारांच्या अधिपत्याखाली होता आणि बहुधा त्यांच्या राज्याची राजधानी गोवा होती. ह्या राजधानीचे स्थलांतर नंतरच्या काळात अधिक मध्यवर्ती स्थान जसेकी रत्नागिरीच्या आसपास अथवा खारेपाटण येथे केले गेले असावे.')
                    assistantt_speaks('चंद्रपूर हे कोकणातील प्राचीन शहरांपैकी एक आहे. ते बहुधा चालुक्य राजा पुल्केशीन दुसरा याचा मुलगा चंद्रादित्यद्वारा स्थापित करण्यात आले होते. सोळाव्या शतकात संपूर्ण पश्चिम किनारपट्टीवर पोर्तुगीज सत्तेचा उदय झाला आणि सिंधुदुर्ग जिल्हा याला काही अपवाद नव्हता. अखेर १६७५ मध्ये सुलतानाच्या हातून हा जिल्हा शिवरायांच्या हाती आला. मराठ्यांनी १८७१ पर्यंत जिल्ह्यावर वर्चस्व राखले मात्र १८७१ मध्ये ब्रिटीश आणि पेशव्यां मधील संघर्ष संपला आणि जिल्हा ब्रिटिशांच्या हातात गेला. ई. स. १८१९ मध्ये दक्षिण कोकण नावाचा वेगळा जिल्हा निर्माण करण्यात आला व त्याचे मुख्यालय प्रथम बाणकोट व नंतर रत्नागिरी येथे ठेवण्यात आले. १८३० मध्ये उत्तरेकडील तीन उपविभाग ठाणे जिल्ह्यात वर्ग केले गेले आणि सिंधुदुर्गला एका उपजिल्ह्याचा दर्जा देण्यात आला.')
                    assistantt_speaks('१८३२ मध्ये रत्नागिरी नावाने एक नवीन जिल्हा निर्माण करण्यात आला.  ई.स.१९४५  मध्ये कणकवली नावाचे एक नवे महल (तहसील) निर्माण करण्यात आले. तद्नंतर ई.स. १९४९ मध्ये पूर्वीच्या सावंतवाडी संस्थानाचे जिल्ह्यात विलीनीकरण करण्यात आले व तालुक्यांच्या सीमा निश्चित करण्यात आल्या.')
                    assistantt_speaks('याच वर्षी सावंतवाडी हा स्वतंत्र तालुका निर्माण करण्यात आला तसेच कुडाळ आणि लांजा असे दोन तहसील ठरवण्यात आले. १९५६  मध्ये राज्यांचे पुनर्वसन होत असताना हा जिल्हा मुंबई प्रांतामध्ये समाविष्ट करण्यात आला व १९६०  पासून तो महाराष्ट्र राज्याचा एक भाग आहे. या जिल्ह्याला येथील प्रसिद्ध ‘सिंधुदुर्ग’ किल्ल्याचे नाव देण्यात आले आहे.')
                    assistantt_speaks(' शिवाजी महाराजांनी मालवण नजीक बांधलेल्या या किल्याचा अर्थ ‘समुद्री किल्ला’ अस होतो.  २५ नोव्हेंबर १६६४  साली सुरु झालेले या किल्ल्याचे बांधकाम तब्बल ३ वर्षांनी अशा रीतीने पूर्ण झाले की अरबी समुद्रा मार्गे येणाऱ्या शत्रूला हा किल्ला दिसणे अवघड होते.')

                elif 'इतीहास' in str(texts):
                    assistantt_speaks('इतिहास')
                    assistantt_speaks('रूपरेखा')
                    assistantt_speaks('सिंधुदुर्ग जिल्हा हा ५,२०७ चौ.किमी. क्षेत्रामध्ये पसरलेला आहे. या जिल्ह्याची लोकसंख्या २००१ च्या जनगणने प्रमाणे ८,६८,८२५ एवढी आहे. आधुनिकीकरण करण्यात आलेले सिंधुदुर्गनगरी हे शहर जिल्ह्याचे मुख्यालय आहे. सिंधुदुर्ग हा पूर्वेकडून अरबी समुद्राने, दक्षिणेकडून बेळगाव जिल्हा (कर्नाटक राज्य) आणि गोवा राज्याने तर उत्तरेकडून रत्नागिरी जिल्ह्याने वेढला गेलेला आहे. हा जिल्हा समुद्र किनारी असल्यामुळे येथील हवामान नेहमी उष्ण व दमट असते त्यामुळे तापमानावर बदलत्या ऋतूंचा फारसा परिणाम होत नाही. येथील कुडाळ,कणकवली व सावंतवाडी या प्रमुख शहरातून जाणारा राष्ट्रीय महामार्ग क्र. तसेच कणकवली, सिंधुदुर्गनगरी, कुडाळ, सावंतवाडी येथील रेल्वे स्थानकांवरून येथे पोचता येते. रत्नागिरी, बेळगाव (कर्नाटक) आणि दाभोली (गोवा) ही जवळील विमानतळे आहेत.')
                    assistantt_speaks('सिंधुदुर्ग जिल्ह्याचा संक्षिप्त इतिहास')
                    assistantt_speaks('सिंधुदुर्ग जिल्हा हा ‘कोकण’ या उंच पठारी प्रदेशाच्या पश्चिमेला असून ऐतिहासीक रीत्या आपल्या लांब तट रेखा आणि सुरक्षित बंदरे यांसाठी प्रसिद्ध आहे. हा जिल्हा पूर्वी रत्नागिरी जिल्ह्याचा एक भाग होता. परंतु  १ मे १९८१  पासून प्रशासकीय सुविधा तसेच औद्योगिक आणि कृषी विकास यांच्या साठी रत्नागिरी आणि सिंधुदुर्ग अशा २ जिल्ह्यात विभागीत करण्यात आला. सिंधुदुर्ग जिल्ह्यात सध्या सावंतवाडी, कुडाळ, वेंगुर्ला, मालवण, देवगड, कणकवली, वैभववाडी आणि दोडामार्ग अशा तहसील केंद्रांचा समावेश होतो. ‘कोंकण’ हा शब्द मुळ भारतीय व पुरातन असून या नावाची पुरेशी माहिती उपलब्ध नाही.')
                    assistantt_speaks('रत्नागिरी जिल्हा हा शिलाहारांच्या अधिपत्याखाली होता आणि बहुधा त्यांच्या राज्याची राजधानी गोवा होती. ह्या राजधानीचे स्थलांतर नंतरच्या काळात अधिक मध्यवर्ती स्थान जसेकी रत्नागिरीच्या आसपास अथवा खारेपाटण येथे केले गेले असावे.')
                    assistantt_speaks('चंद्रपूर हे कोकणातील प्राचीन शहरांपैकी एक आहे. ते बहुधा चालुक्य राजा पुल्केशीन दुसरा याचा मुलगा चंद्रादित्यद्वारा स्थापित करण्यात आले होते. सोळाव्या शतकात संपूर्ण पश्चिम किनारपट्टीवर पोर्तुगीज सत्तेचा उदय झाला आणि सिंधुदुर्ग जिल्हा याला काही अपवाद नव्हता. अखेर १६७५ मध्ये सुलतानाच्या हातून हा जिल्हा शिवरायांच्या हाती आला. मराठ्यांनी १८७१ पर्यंत जिल्ह्यावर वर्चस्व राखले मात्र १८७१ मध्ये ब्रिटीश आणि पेशव्यां मधील संघर्ष संपला आणि जिल्हा ब्रिटिशांच्या हातात गेला. ई. स. १८१९ मध्ये दक्षिण कोकण नावाचा वेगळा जिल्हा निर्माण करण्यात आला व त्याचे मुख्यालय प्रथम बाणकोट व नंतर रत्नागिरी येथे ठेवण्यात आले. १८३० मध्ये उत्तरेकडील तीन उपविभाग ठाणे जिल्ह्यात वर्ग केले गेले आणि सिंधुदुर्गला एका उपजिल्ह्याचा दर्जा देण्यात आला.')
                    assistantt_speaks('१८३२ मध्ये रत्नागिरी नावाने एक नवीन जिल्हा निर्माण करण्यात आला.  ई.स.१९४५  मध्ये कणकवली नावाचे एक नवे महल (तहसील) निर्माण करण्यात आले. तद्नंतर ई.स. १९४९ मध्ये पूर्वीच्या सावंतवाडी संस्थानाचे जिल्ह्यात विलीनीकरण करण्यात आले व तालुक्यांच्या सीमा निश्चित करण्यात आल्या.')
                    assistantt_speaks('याच वर्षी सावंतवाडी हा स्वतंत्र तालुका निर्माण करण्यात आला तसेच कुडाळ आणि लांजा असे दोन तहसील ठरवण्यात आले. १९५६  मध्ये राज्यांचे पुनर्वसन होत असताना हा जिल्हा मुंबई प्रांतामध्ये समाविष्ट करण्यात आला व १९६०  पासून तो महाराष्ट्र राज्याचा एक भाग आहे. या जिल्ह्याला येथील प्रसिद्ध ‘सिंधुदुर्ग’ किल्ल्याचे नाव देण्यात आले आहे.')
                    assistantt_speaks(' शिवाजी महाराजांनी मालवण नजीक बांधलेल्या या किल्याचा अर्थ ‘समुद्री किल्ला’ अस होतो.  २५ नोव्हेंबर १६६४  साली सुरु झालेले या किल्ल्याचे बांधकाम तब्बल ३ वर्षांनी अशा रीतीने पूर्ण झाले की अरबी समुद्रा मार्गे येणाऱ्या शत्रूला हा किल्ला दिसणे अवघड होते.')

                elif 'जिल्ह्याचा नकाशा' in str(texts):
                    webbrowser.open('https://sindhudurg.nic.in/%e0%a4%9c%e0%a4%bf%e0%a4%b2%e0%a5%8d%e0%a4%b9%e0%a5%8d%e0%a4%af%e0%a4%be%e0%a4%b5%e0%a4%bf%e0%a4%b7%e0%a4%af%e0%a5%80/%e0%a4%9c%e0%a4%bf%e0%a4%b2%e0%a5%8d%e0%a4%b9%e0%a5%8d%e0%a4%af%e0%a4%be%e0%a4%9a%e0%a4%be-%e0%a4%a8%e0%a4%95%e0%a4%be%e0%a4%b6%e0%a4%be/')
                    assistantt_speaks('जिल्ह्याचा नकाशा उघडला आहे')

                elif 'कोण कोण आहे' in str(texts):
                    assistantt_speaks('जिल्हाधिकारी कार्यालयात')
                    var.set('जिल्हाधिकारी कार्यालयात')
                    window.update()
                    assistantt_speaks('उप विभागीय अधिकारी')
                    var.set('उप विभागीय अधिकारी')
                    window.update()
                    assistantt_speaks('तहसिलदार')
                    var.set('तहसिलदार')
                    window.update()
                    assistantt_speaks('जिल्हा परिषद सिंधुदुर्ग')
                    var.set('जिल्हा परिषद सिंधुदुर्ग')
                    window.update()
                    assistantt_speaks('पोलीस अधीक्षक सिंधुदुर्ग')
                    var.set('पोलीस अधीक्षक सिंधुदुर्ग')
                    window.update()
                    assistantt_speaks('तुम्हाला कोणाची माहिती हवी आहे')
                    textt = get_audios()

                    if 'जिल्हाधिकारी कार्यालय' in str(textt):
                        assistantt_speaks('जिल्हाधिकारी कार्यालयात समाविष्ट आहे')
                        assistantt_speaks('जिल्हाधिकारी सिंधुदुर्ग')
                        var.set('जिल्हाधिकारी सिंधुदुर्ग')
                        window.update()
                        assistantt_speaks('अपर जिल्हाधिकारी')
                        var.set('अपर जिल्हाधिकारी')
                        window.update()
                        assistantt_speaks('निवासी उपजिल्हाधिकारी')
                        var.set('निवासी उपजिल्हाधिकारी')
                        window.update()
                        assistantt_speaks('जिल्हा पुरवठा अधिकारी')
                        var.set('जिल्हा पुरवठा अधिकारी')
                        window.update()
                        assistantt_speaks('तुम्हाला कोणाची माहिती हवी आहे?')
                        texxt = get_audios()
                        
                        if 'जिल्हाधिकारी सिंधुदुर्ग' in str(texxt):
                            assistantt_speaks('नाव')
                            assistantt_speaks('श्रीम. के. मंजुलक्ष्मी, भा.प्र.से.')
                            var.set('श्रीम. के. मंजुलक्ष्मी, भा.प्र.से.')
                            window.update()
                            assistantt_speaks('ईमेल')
                            assistantt_speaks('pacollsin[at]gmail[dot]com')
                            var.set('pacollsin[at]gmail[dot]com')
                            window.update()
                            assistantt_speaks('दूरध्वनी')
                            assistantt_speaks('02362228844')
                            var.set('02362228844')
                            window.update()

                        elif 'अपर' in str(texxt):
                            assistantt_speaks('नाव')
                            assistantt_speaks('श्री.मंगेश जोशी')
                            var.set('श्री.मंगेश जोशी')
                            window.update()
                            assistantt_speaks('ईमेल')
                            assistantt_speaks('colleststn02[dot]si-mh[at]nic[dot]in')
                            var.set('colleststn02[dot]si-mh[at]nic[dot]in')
                            window.update()
                            assistantt_speaks('दूरध्वनी')
                            assistantt_speaks('02362228855')
                            var.set('02362228855')
                            window.update()

                        elif 'निवासी' in str(texxt):
                            assistantt_speaks('नाव')
                            assistantt_speaks('श्रीम. शुभांगी अनिल साठे .')
                            var.set('श्रीम. शुभांगी अनिल साठे')
                            window.update()
                            assistantt_speaks('ईमेल')
                            assistantt_speaks('collrdc[dot]si-mh[at]gov[dot]in')
                            var.set('collrdc[dot]si-mh[at]gov[dot]in')
                            window.update()
                            assistantt_speaks('दूरध्वनी')
                            assistantt_speaks('02362228845')
                            var.set('02362228845')
                            window.update()

                        elif 'उपजिल्हाधिकारी' in str(texxt):
                            assistantt_speaks('नाव')
                            assistantt_speaks('श्रीम. शुभांगी अनिल साठे .')
                            var.set('श्रीम. शुभांगी अनिल साठे')
                            window.update()
                            assistantt_speaks('ईमेल')
                            assistantt_speaks('collrdc[dot]si-mh[at]gov[dot]in')
                            var.set('collrdc[dot]si-mh[at]gov[dot]in')
                            window.update()
                            assistantt_speaks('दूरध्वनी')
                            assistantt_speaks('02362228845')
                            var.set('02362228845')
                            window.update()
                        
                        elif 'जिल्हा पुरवठा' in str(texxt):
                            assistantt_speaks('नाव')
                            assistantt_speaks('श्री. दादासाहेब रघुनाथ गिते')
                            var.set('श्री. दादासाहेब रघुनाथ गिते')
                            window.update()
                            assistantt_speaks('ईमेल')
                            assistantt_speaks('dsosindhudurg[at]yahoo[dot]com')
                            var.set('dsosindhudurg[at]yahoo[dot]com')
                            window.update()
                            assistantt_speaks('दूरध्वनी')
                            assistantt_speaks('02362228846')
                            var.set('02362228846')
                            window.update()

                        elif 'None' in str(texxt):
                            get_audios()    

                    
                    elif 'उप विभागीय अधिकारी' in str(textt):
                        assistantt_speaks('उप विभागीय अधिकारी समाविष्ट आहे')
                        assistantt_speaks('उप विभागीय अधिकारी कुडाळ')
                        var.set('उप विभागीय अधिकारी कुडाळ')
                        window.update()
                        assistantt_speaks('उप विभागीय अधिकारी कणकवली')
                        var.set('उप विभागीय अधिकारी कणकवली')
                        window.update()
                        assistantt_speaks('उप विभागीय अधिकारी सावंतवाडी')
                        var.set('उप विभागीय अधिकारी सावंतवाडी')
                        window.update()
                        assistantt_speaks('तुम्हला कोणत्या क्षेत्राची माहिती हवी आहे ?')
                        texxt = get_audios()

                        
                        if 'कुडाळ' in str(texxt):
                            assistantt_speaks('नाव')
                            assistantt_speaks('श्रीम. वंदना खरमाळे.')
                            var.set('श्रीम. वंदना खरमाळे')
                            window.update()
                            assistantt_speaks('ईमेल')
                            assistantt_speaks('sdokudal[at]gmail[dot]com')
                            var.set('sdokudal[at]gmail[dot]com')
                            assistantt_speaks('दूरध्वनी')
                            assistantt_speaks('02362223325')
                            var.set('02362223325')
                            window.update()

                        elif 'कणकवली' in str(texxt):
                            assistantt_speaks('नाव')
                            assistantt_speaks('श्रीम. वैशाली राजमाने.')
                            var.set('श्रीम. वैशाली राजमाने.')
                            window.update()
                            assistantt_speaks('ईमेल')
                            assistantt_speaks('sdokankavali[at]gmail[dot]com')
                            var.set('sdokankavali[at]gmail[dot]com')
                            window.update()
                            assistantt_speaks('दूरध्वनी')
                            assistantt_speaks('02367232092')
                            var.set('02367232092')
                            window.update()
                        
                        elif 'सावंतवाडी' in str(texxt):
                            assistantt_speaks('नाव')
                            assistantt_speaks('श्री. सुशांत खांडेकर')
                            var.set('श्री. सुशांत खांडेकर')
                            window.update()
                            assistantt_speaks('ईमेल')
                            assistantt_speaks('sdosawantwadi[at]gmail[dot]com')
                            var.set('sdosawantwadi[at]gmail[dot]com')
                            window.update()
                            assistantt_speaks('दूरध्वनी')
                            assistantt_speaks('02363272029')
                            var.set('02363272029')
                            window.update()

                        elif 'None' in str(texxt):
                            get_audios()

                    elif 'तहसीलदार' in str(textt):
                        assistantt_speaks('तहसिलदार समाविष्ट ')
                        assistantt_speaks('तहसिलदार देवगड')
                        var.set('तहसिलदार देवगड')
                        window.update()
                        assistantt_speaks('तहसिलदार वैभववाडी')
                        var.set('तहसिलदार वैभववाडी')
                        window.update()
                        assistantt_speaks('तहसिलदार कुडाळ')
                        var.set('तहसिलदार कुडाळ')
                        window.update()
                        assistantt_speaks('तहसिलदार मालवण')
                        var.set('तहसिलदार मालवण')
                        window.update()
                        assistantt_speaks('तहसिलदार कणकवली')
                        var.set('तहसिलदार कणकवली')
                        window.update()
                        assistantt_speaks('तहसिलदार वेंगुर्ला')
                        var.set('तहसिलदार वेंगुर्ला')
                        window.update()
                        assistantt_speaks('तहसिलदार सावंतवाडी')
                        var.set('तहसिलदार सावंतवाडी')
                        window.update()
                        assistantt_speaks('तहसिलदार दोडामार्ग')
                        var.set('तहसिलदार दोडामार्ग')
                        window.update()
                        assistantt_speaks('तुम्हाला कोणाची माहिती हवी आहे?')
                        texxt = get_audios()

                        
                        if 'देवगड' in str(texxt):
                            assistantt_speaks('नाव')
                            assistantt_speaks('श्री. मारुती कांबळे.')
                            var.set('श्री. मारुती कांबळे')
                            window.update()
                            assistantt_speaks('ईमेल')
                            assistantt_speaks('tahsildardevgad[at]gmail[dot]com')
                            var.set('tahsildardevgad[at]gmail[dot]com')
                            window.update()
                            assistantt_speaks('दूरध्वनी')
                            assistantt_speaks('02364262204')
                            var.set('02364262204')
                            window.update()

                        elif 'वैभववाडी' in str(texxt):
                            assistantt_speaks('नाव')
                            assistantt_speaks('श्री. रामदास झालके')
                            var.set('श्री. रामदास झालके')
                            assistantt_speaks('ईमेल')
                            assistantt_speaks('tvaitah[at]gmail[dot]com')
                            var.set('tvaitah[at]gmail[dot]com')
                            window.update()
                            assistantt_speaks('दूरध्वनी')
                            assistantt_speaks('02367237239')
                            var.set('02367237239')
                            window.update()

                        elif 'कुडाळ' in str(texxt):
                            assistantt_speaks('नाव')
                            assistantt_speaks('श्री. रवींद्र नाचणकर .')
                            var.set('श्री. रवींद्र नाचणकर ')
                            assistantt_speaks('ईमेल')
                            assistantt_speaks('tahsilkudal123[at]gmail[dot]com')
                            var.set('tahsilkudal123[at]gmail[dot]com')
                            window.update()
                            assistantt_speaks('दूरध्वनी')
                            assistantt_speaks('02362222525')
                            var.set('02362222525')
                            window.update()

                        elif 'मालवण' in str(texxt):
                            assistantt_speaks('नाव')
                            assistantt_speaks('श्री. अजय पाटणे .')
                            var.set('श्री. अजय पाटणे')
                            assistantt_speaks('ईमेल')
                            assistantt_speaks('tahasilmalvan[at]gmail[dot]com')
                            var.set('tahasilmalvan[at]gmail[dot]com')
                            window.update()
                            assistantt_speaks('दूरध्वनी')
                            assistantt_speaks('02365252045')
                            var.set('02365252045')
                            window.updaate()

                        elif 'कणकवली' in str(texxt):
                            assistantt_speaks('नाव')
                            assistantt_speaks('श्री. रमेश जे. पवार.')
                            var.set('श्री. रमेश जे. पवार.')
                            assistantt_speaks('ईमेल')
                            assistantt_speaks('tahsilkankavali[at]gmail[dot]com')
                            var.set('tahsilkankavali[at]gmail[dot]com')
                            window.update()
                            assistantt_speaks('दूरध्वनी')
                            assistantt_speaks('02367232025')
                            var.set('02367232025')
                            window.update()

                        elif 'वेंगुर्ला' in str(texxt):
                            assistantt_speaks('नाव')
                            assistantt_speaks('श्री. प्रवीण लोकरे .')
                            var.set('श्री. प्रवीण लोकरे .')
                            assistantt_speaks('ईमेल')
                            assistantt_speaks('tahvgl[at]gmail[dot]com')
                            var.set('tahvgl[at]gmail[dot]com')
                            window.update()
                            assistantt_speaks('दूरध्वनी')
                            assistantt_speaks('02366262053')
                            var.set('02366262053')
                            window.update()

                        elif 'सावंतवाडी' in str(texxt):
                            assistantt_speaks('नाव')
                            assistantt_speaks('श्री. राजाराम म्हात्रे')
                            var.set('श्री. राजाराम म्हात्रे')
                            window.update()
                            assistantt_speaks('ईमेल')
                            assistantt_speaks('tahsilsawantwadi[at]gmail[dot]com')
                            var.set('tahsilsawantwadi[at]gmail[dot]com')
                            window.update()
                            assistantt_speaks('दूरध्वनी')
                            assistantt_speaks('02363272028')
                            var.set('02363272028')
                            window.update()

                        elif ' दोडामार्ग' in str(texxt):
                            assistantt_speaks('नाव')
                            assistantt_speaks('श्री. मोरेश्वर रा. हाडके .')
                            var.set('श्री. मोरेश्वर रा. हाडके .')
                            window.update()
                            assistantt_speaks('ईमेल')
                            assistantt_speaks('tahsildodamarg[at]gmail[dot]com')
                            var.set('tahsildodamarg[at]gmail[dot]com')
                            window.update()
                            assistantt_speaks('दूरध्वनी')
                            assistantt_speaks('02363256518')
                            var.set('02363256518')
                            window.update()

                        elif 'None' in str(texxt):
                            get_audios()

                    elif 'जिल्हा परिषद सिंधुदुर्ग' in str(textt):
                        assistantt_speaks('जिल्हा परिषद समाविष्ट')
                        assistantt_speaks('अध्यक्ष जि.प.सिंधुदुर्ग')
                        var.set('अध्यक्ष जि.प.सिंधुदुर्ग')
                        window.update()
                        assistantt_speaks('मुख्य कार्यकारी अधिकारी')
                        var.set('मुख्य कार्यकारी अधिकारी')
                        window.update()
                        assistantt_speaks('तुम्हाला कोणत्या जिल्हा परिषद ची माहिती हवी आहे?')
                        texxt = get_audios()

                        
                        if 'अध्यक्ष' in str(texxt):
                            assistantt_speaks('नाव')
                            assistantt_speaks('मा. श्रीम. समिधा स. नाईक .')
                            var.set('मा. श्रीम. समिधा स. नाईक .')
                            window.update()                    
                            assistantt_speaks('ईमेल')
                            assistantt_speaks('presidentsindhudurg[at]gmail[dot]com')
                            var.set('presidentsindhudurg[at]gmail[dot]com')
                            window.update()
                            assistantt_speaks('दूरध्वनी')
                            assistantt_speaks('02362-228813')
                            var.set('02362-228813')
                            window.update()
                        
                        elif 'मुख्य' in str(texxt):
                            assistantt_speaks('नाव')
                            assistantt_speaks('डॉ. हेमंत वसेकर . (भा.प्र.से.)')
                            var.set('डॉ. हेमंत वसेकर . (भा.प्र.से.)')
                            window.update()
                            assistantt_speaks('ईमेल')
                            assistantt_speaks('ceozpsindhudurg[at]gmail[dot]com')
                            var.set('ceozpsindhudurg[at]gmail[dot]com')
                            window.update()
                            assistantt_speaks('दूरध्वनी')
                            assistantt_speaks('02362228807')
                            var.set('02362228807')
                            window.update()

                        elif'None' in str(texxt):
                            get_audios()

                    elif 'पोलीस' in str(textt): #अधीक्षक सिंधुदुर्ग
                        assistantt_speaks('नाव')
                        assistantt_speaks('श्री. दीक्षित गेडाम. (भा.पो.से.)')
                        assistantt_speaks('पदनाम')
                        assistantt_speaks('पोलीस अधिक्षक सिंधुदुर्ग	')
                        assistantt_speaks('ईमेल')
                        assistantt_speaks('sp[dot]sindhudurg[at]mahapolice[dot]gov[dot]in')
                        assistantt_speaks('दूरध्वनी')
                        assistantt_speaks('02362228201')

                    elif 'None' in str(textt):
                        get_audios()


                elif 'लोकप्रतिनिधी' in str(texts):
                    assistantt_speaks('लोकप्रतिनिधी समाविष्ट')
                    assistantt_speaks('पालकमंत्री सिंधुदुर्ग जिल्हा')
                    var.set('पालकमंत्री सिंधुदुर्ग जिल्हा')
                    window.update()
                    assistantt_speaks('खासदार - लोकसभा')
                    var.set('खासदार - लोकसभा')
                    window.update()
                    assistantt_speaks('आमदार - विधानसभा')
                    var.set('आमदार - विधानसभा')
                    window.update()
                    assistantt_speaks('खासदार - राज्यसभा')
                    var.set('खासदार - राज्यसभा')
                    window.update()
                    assistantt_speaks('तुम्हाला कोणाची माहिती हवी आहे?')
                    textt = get_audios()
                    
                    if 'पालकमंत्री' in str(textt):
                        assistantt_speaks('मा.श्री. उदय रवींद्र सामंत .')
                        assistantt_speaks('उच्च व तंत्र शिक्षण मंत्री तथा पालकमंत्री सिंधुदुर्ग जिल्हा')
                    elif 'खासदार' in str(textt):
                        assistantt_speaks('मा.श्री.विनायक बाबुराव राऊत .')
                        assistantt_speaks('लोकसभा मतदारसंघ - रत्नागिरी -सिंधुदुर्ग ')
                        assistantt_speaks('मु.पो.सुकळवाड , तळगाव , राऊतवाडी ता.मालवण जि.सिंधुदुर्ग ')
                        assistantt_speaks('दूरध्वनी - ०२३५२२२०४२५ किंवा ०२३६५२२५३००')
                    elif 'लोकसभा' in str(textt):
                        assistantt_speaks('मा.श्री.विनायक बाबुराव राऊत .')
                        assistantt_speaks('लोकसभा मतदारसंघ - रत्नागिरी -सिंधुदुर्ग ')
                        assistantt_speaks('मु.पो.सुकळवाड , तळगाव , राऊतवाडी ता.मालवण जि.सिंधुदुर्ग ')
                        assistantt_speaks('दूरध्वनी - ०२३५२२२०४२५ किंवा ०२३६५२२५३००')
                    elif 'आमदार विधानसभा' in str(textt):
                            assistantt_speaks('तुम्हाला कोणती मतदारसंघ माहिती हवी आहे?')
                            assistantt_speaks('कणकवली')
                            var.set('कणकवली')
                            window.update()
                            assistantt_speaks(' कुडाळ ')
                            var.set(' कुडाळ ')
                            window.update()
                            assistantt_speaks('सावंतवाडी')
                            var.set('सावंतवाडी')
                            window.update()
                            texxt = get_audios()

                            

                            if 'कणकवली' in str(texxt):
                                assistantt_speaks('मा.श्री. नितेश नारायण राणे')
                                assistantt_speaks('विधानसभा मतदारसंघ - कणकवली')
                                assistantt_speaks('घर.क्र.१७९ फलसियेवाडी फणसनगर ता.कणकवली .जि.सिंधुदुर्ग')
                                assistantt_speaks('दूरध्वनी ०२२-२६०५३२८० / ६३')
                            elif 'कुडाळ ' in str(texxt):
                                assistantt_speaks('मा.श्री.वैभव विजय नाईक ')                                    
                                assistantt_speaks(' विधानसभा मतदारसंघ - कुडाळ ')
                                assistantt_speaks('८४ नाथ पै नगर , बिजली नगर , हायवे जवळ मु.पो.ता.कणकवली जि.सिंधुदुर्ग . ')
                                assistantt_speaks('दूरध्वनी ०२३६७२३२५३५')
                            elif 'सावंतवाडी' in str(texxt):
                                assistantt_speaks('मा.श्री.दिपक वसंत केसरकर')
                                assistantt_speaks('विधानसभा मतदारसंघ -सावंतवाडी')
                                assistantt_speaks('श्रीधर अपा. एस.टी.स्थानकाजवळ मु.पो.ता.सावंतवाडी .जि.सिंधुदुर्ग')
                                assistantt_speaks('ई-मेल - kesarkardeepak[at]yahoo[dot]com ')
                                assistantt_speaks('दूरध्वनी ०२३६३-२७३७१६ , २७३७१२')

                            elif "None" in str(texxt):
                                get_audios()
                                
                        
                    elif 'राज्यसभा' in str(textt):
                        assistantt_speaks('मा.श्री.नारायण तातू राणे.')
                        assistantt_speaks('घर.क्र.१७९ फलसियेवाडी फणसनगर ता.कणकवली .जि.सिंधुदुर्ग')
                        assistantt_speaks('दूरध्वनी ०२२-२६०५३२८० / ६३')

                    elif'None' in str(textt):
                        get_audios()    

                elif 'None' in str(texts):
                    get_audios()


            elif 'सुविधा' in str(text):
                assistantt_speaks('तुम्हाला कोणत्या सावर्जनिक सुविधा हवे आहे ?')
                assistantt_speaks('हेल्पलाईन नंबर ')
                var.set('हेल्पलाईन नंबर')
                window.update()
                assistantt_speaks('सुविद्या')
                var.set('सुविद्या')
                window.update()
                t = get_audios()

                

                if 'नंबर' in str(t):
                    assistantt_speaks('जिल्हाधिकारी सिंधुदुर्ग')
                    var.set('जिल्हाधिकारी सिंधुदुर्ग')
                    window.update()
                    assistantt_speaks('नाव')
                    assistantt_speaks('श्रीम. के. मंजुलक्ष्मी, भा.प्र.से.')
                    var.set('श्रीम. के. मंजुलक्ष्मी, भा.प्र.से.')
                    window.update()
                    assistantt_speaks('ईमेल')
                    assistantt_speaks('pacollsin[at]gmail[dot]com')
                    var.set('pacollsin[at]gmail[dot]com')
                    window.update()
                    assistantt_speaks('दूरध्वनी')
                    assistantt_speaks('02362228844')
                    var.set('02362228844')
                    window.update()
                    assistantt_speaks('अपर जिल्हाधिकारी')
                    var.set('अपर जिल्हाधिकारी')
                    window.update()
                    assistantt_speaks('नाव')
                    assistantt_speaks('श्री.मंगेश जोशी')
                    var.set('श्री.मंगेश जोशी')
                    window.update()
                    assistantt_speaks('ईमेल')
                    assistantt_speaks('colleststn02[dot]si-mh[at]nic[dot]in')
                    var.set('colleststn02[dot]si-mh[at]nic[dot]in')
                    window.update()
                    assistantt_speaks('दूरध्वनी')
                    assistantt_speaks('02362228855')
                    var.set('02362228855')
                    window.update()
                    assistantt_speaks('निवासी उपजिल्हाधिकारी')
                    var.set('निवासी उपजिल्हाधिकारी')
                    window.update()
                    assistantt_speaks('नाव')
                    assistantt_speaks('श्रीम. शुभांगी अनिल साठे .')
                    var.set('श्रीम. शुभांगी अनिल साठे')
                    window.update()
                    assistantt_speaks('ईमेल')
                    assistantt_speaks('collrdc[dot]si-mh[at]gov[dot]in')
                    var.set('collrdc[dot]si-mh[at]gov[dot]in')
                    window.update()
                    assistantt_speaks('दूरध्वनी')
                    assistantt_speaks('02362228845')
                    var.set('02362228845')
                    window.update()

                elif 'सुविद्या' in str(t):
                    assistantt_speaks('तुम्हाला कोणत्या सुविधा हवाय')
                    assistantt_speaks('बँक ')
                    var.set('बँक ')
                    window.update()
                    assistantt_speaks('महाविद्यालय किंवा विद्यापीठ')
                    var.set('महाविद्यालय किंवा विद्यापीठ')
                    window.update()
                    assistantt_speaks('वीज ')
                    var.set('वीज ')
                    window.update()
                    assistantt_speaks('रुग्णालय')
                    var.set('रुग्णालय')
                    window.update()
                    assistantt_speaks('नगरपालिका ')
                    var.set('नगरपालिका ')
                    window.update()
                    assistantt_speaks('अ-शासकीय संस्था')
                    var.set('अ-शासकीय संस्था')
                    window.update()
                    assistantt_speaks('टपाल')
                    var.set('टपाल')
                    window.update()
                    assistantt_speaks('शाळा')
                    var.set('शाळा')
                    window.update()
                    te = get_audios()
                    
                    if 'बँक' in str(te):
                        assistantt_speaks('तुम्हाला कोणत्या बँकेबद्दल जाणून घ्यायचे आहे?')
                        assistantt_speaks('एस.बी.आय.')
                        var.set('एस.बी.आय.')
                        window.update()
                        assistantt_speaks('कोर्पोरेशन बँक')
                        var.set('कोर्पोरेशन बँक')
                        window.update()
                        assistantt_speaks('सिंधुदुर्ग जिल्हा मध्यवर्ती सहकारी बँक व मुख्यालय ')
                        var.set('सिंधुदुर्ग जिल्हा मध्यवर्ती सहकारी बँक व मुख्यालय ')
                        window.update()
                        tex = get_audios()
                        
                        if 'एस बी आय' in str(tex):
                            assistantt_speaks('बँक पत्ता')
                            assistantt_speaks('सिंधुदुर्गनगरी शाखा . मु .पो.ओरोस . सिंधुदुर्गनगरी . ता.कुडाळ . जि . सिंधुदुर्ग. पिन. ४१६८१२')
                            assistantt_speaks('दूरध्वनी क्रमांक')
                            assistantt_speaks('02362-228744')
                            var.set('02362-228744')
                            window.update()
                        elif 'कोर्पोरेशन बँक' in str(tex):
                            assistantt_speaks('बँक पत्ता')
                            assistantt_speaks('मुंबई-गोवा हायवे , खार्ये वाडी , ओरोस पिन.४१६८१२')
                            assistantt_speaks('दूरध्वनी क्रमांक')
                            assistantt_speaks('02362-228023')
                            var.set('02362-228023')
                            window.update()
                            webbrowser.open('https://www.corpbank.com/')
                            assistantt_speaks('या बँकेसाठी वेबसाइट उघडली गेली आहे')
                        elif 'सिंधुदुर्ग' in str(tex):
                            assistantt_speaks('बँक पत्ता')
                            assistantt_speaks('मु.पो.ओरोस . सिंधुदुर्गनगरी ता.कुडाळ . जिल्हा सिंधुदुर्ग . पिन .४१६८')
                            assistantt_speaks('दूरध्वनी क्रमांक')
                            assistantt_speaks('02362-229005')
                            var.set('02362-229005')
                            window.update()

                        elif 'None' in str(tex):
                            get_audios()


                    elif 'महाविद्यालय ' in str(te):
                        assistantt_speaks('तुम्हाला कोणत्या विद्यापीठाच्या जाणून घ्यायचे आहे?')
                        assistantt_speaks('एम .आय.टी.एम. अभियांत्रिकी महाविद्यालय .')
                        var.set('एम .आय.टी.एम. अभियांत्रिकी महाविद्यालय .')
                        window.update()
                        assistantt_speaks('एस.एस.पी.एम. मेडिकल कॉलेज')
                        var.set('एस.एस.पी.एम. मेडिकल कॉलेज')
                        window.update()
                        assistantt_speaks('डी. एड व बी. एड. महाविद्यालय ४ + १')
                        var.set('डी. एड व बी. एड. महाविद्यालय ४ + १')
                        window.update()
                        assistantt_speaks('तंत्र निकेतन महाविद्यालय मालवण')
                        var.set('तंत्र निकेतन महाविद्यालय मालवण')
                        window.update()
                        assistantt_speaks('भाई साहेब सावंत आयुर्वेदिक महाविद्यालय')
                        var.set('भाई साहेब सावंत आयुर्वेदिक महाविद्यालय')
                        window.update()
                        assistantt_speaks('महाविद्यालय २१ , कनिष्ठ महाविद्यालय ४३')
                        var.set('महाविद्यालय २१ , कनिष्ठ महाविद्यालय ४३')
                        window.update()
                        assistantt_speaks('शासकीय औद्योगिक प्रशिक्षण संस्था .')
                        var.set('शासकीय औद्योगिक प्रशिक्षण संस्था .')
                        window.update()
                        assistantt_speaks('सिंधुदुर्ग शिक्षण प्रसारक , अभियांत्रिकी महाविद्यालय')
                        var.set('सिंधुदुर्ग शिक्षण प्रसारक , अभियांत्रिकी महाविद्यालय')
                        window.update()
                        assistantt_speaks('होमिओपॅथी वैद्यकीय महाविद्यालय.')
                        var.set('होमिओपॅथी वैद्यकीय महाविद्यालय.')
                        window.update()
                        tet = get_audios()
                        
                        if 'एम आय टी एम ' in str(tet): #अभियांत्रिकी'
                            assistantt_speaks('विद्यापीठाच्या नाव')
                            assistantt_speaks('एम .आय.टी.एम. अभियांत्रिकी महाविद्यालय .')
                            var.set('एम .आय.टी.एम. अभियांत्रिकी महाविद्यालय .')
                            window.update()
                            assistantt_speaks('विद्यापीठाच्या पत्ता')
                            assistantt_speaks('सुकळवाड , ओरोस रेल्वे स्थानक जवळ , ता. मालवण .जि.सिंधुदुर्ग .पिन. ४१६५३४')
                            var.set('सुकळवाड , ओरोस रेल्वे स्थानक जवळ , ता. मालवण .जि.सिंधुदुर्ग .पिन. ४१६५३४')
                            window.update()
                            assistantt_speaks('दूरध्वनी ')
                            assistantt_speaks('02362-228551')
                            var.set('02362-228551')
                            window.update()

                        elif 'मेडिकल' in str(tet):
                            assistantt_speaks('विद्यापीठाच्या नाव')
                            assistantt_speaks('एस.एस.पी.एम. मेडिकल कॉलेज')
                            var.set('एस.एस.पी.एम. मेडिकल कॉलेज')
                            window.update()
                            assistantt_speaks('विद्यापीठाच्या पत्ता')
                            assistantt_speaks('पडवे . मालवण -कसाल रोड , रानबाम्बुली , ता.कुडाळ .जि. सिंधुदुर्ग .')
                            var.set('पडवे . मालवण -कसाल रोड , रानबाम्बुली , ता.कुडाळ .जि. सिंधुदुर्ग .')
                            window.update()
                            assistantt_speaks('दूरध्वनी')
                            assistantt_speaks('02367-234000')
                            var.set('02367-234000')
                            window.update()

                        elif 'बी एड' in str(tet):
                            assistantt_speaks('विद्यापीठाच्या नाव')
                            assistantt_speaks('डी. एड व बी. एड. महाविद्यालय ४ + १')
                            var.set('डी. एड व बी. एड. महाविद्यालय ४ + १')
                            window.update()
                            assistantt_speaks('विद्यापीठाच्या पत्ता')
                            assistantt_speaks('सिंधुदुर्ग जिल्हा')
                            var.set('सिंधुदुर्ग जिल्हा')
                            window.update()
                        elif 'तंत्र निकेतन ' in str(tet): #महाविद्यालय
                            assistantt_speaks('विद्यापीठाच्या नाव')
                            assistantt_speaks('तंत्र निकेतन महाविद्यालय मालवण')
                            var.set('तंत्र निकेतन महाविद्यालय मालवण')
                            window.update()
                            assistantt_speaks('विद्यापीठाच्या पत्ता')
                            assistantt_speaks('मु.पो.कुंभारमाठ . ता.मालवण . जिल्हा .सिंधुदुर्ग . पिन .४१६६०६')
                            var.set('मु.पो.कुंभारमाठ . ता.मालवण . जिल्हा .सिंधुदुर्ग . पिन .४१६६०६')
                            window.update()
                            assistantt_speaks('दूरध्वनी')
                            assistantt_speaks(' 02365-252223')
                            var.set(' 02365-252223')
                            window.update()
                        elif 'आयुर्वेदिक ' in str(tet):
                            assistantt_speaks('विद्यापीठाच्या नाव')
                            assistantt_speaks('भाई साहेब सावंत आयुर्वेदिक महाविद्यालय')
                            var.set('भाई साहेब सावंत आयुर्वेदिक महाविद्यालय')
                            window.update()
                            assistantt_speaks('विद्यापीठाच्या पत्ता')
                            assistantt_speaks('मुंबई-गोवा रस्ता , खासकीलवाडा ,मु.पो.ता.सावंतवाडी जि.सिंधुदुर्ग .पिन.४१६५१० .')
                            var.set('मुंबई-गोवा रस्ता , खासकीलवाडा ,मु.पो.ता.सावंतवाडी जि.सिंधुदुर्ग .पिन.४१६५१० .')
                            window.update()
                            assistantt_speaks('दूरध्वनी')
                            assistantt_speaks('02363-272302')
                            var.set('02363-272302')
                            window.update()
                        elif 'महाविद्यालय' in str(tet):
                            assistantt_speaks('विद्यापीठाच्या नाव')
                            assistantt_speaks('महाविद्यालय २१ , कनिष्ठ महाविद्यालय ४३')
                            var.set('महाविद्यालय २१ , कनिष्ठ महाविद्यालय ४३')
                            window.update()
                            assistantt_speaks('विद्यापीठाच्या पत्ता')
                            assistantt_speaks('सिंधुदुर्ग जिल्हा')
                            var.set('सिंधुदुर्ग जिल्हा')
                            window.update()
                            
                        elif 'शासकीय  ' in str(tet): #औद्योगिक प्रशिक्षण
                            assistantt_speaks('विद्यापीठाच्या नाव')
                            assistantt_speaks('शासकीय औद्योगिक प्रशिक्षण संस्था .')
                            var.set('शासकीय औद्योगिक प्रशिक्षण संस्था .')
                            window.update()
                            assistantt_speaks('विद्यापीठाच्या पत्ता')
                            assistantt_speaks('मु.पो.ओरोस . सिंधुदुर्गनगरी ता.कुडाळ . जिल्हा सिंधुदुर्ग . पिन .४१६८१२')
                            var.set('मु.पो.ओरोस . सिंधुदुर्गनगरी ता.कुडाळ . जिल्हा सिंधुदुर्ग . पिन .४१६८१२')
                            window.update()
                            assistantt_speaks('दूरध्वनी')
                            assistantt_speaks('02362-228090')
                            var.set('02362-228090')
                            window.update()
                        elif 'अभियांत्रिकी' in str(tet):
                            assistantt_speaks('विद्यापीठाच्या नाव')
                            assistantt_speaks('सिंधुदुर्ग शिक्षण प्रसारक , अभियांत्रिकी महाविद्यालय')
                            var.set('सिंधुदुर्ग शिक्षण प्रसारक , अभियांत्रिकी महाविद्यालय')
                            window.update()
                            assistantt_speaks('विद्यापीठाच्या पत्ता')
                            assistantt_speaks('पो.हरकुळ बु. ता.कणकवली .जि.सिंधुदुर्ग पिन. ४१६६०२')
                            var.set('पो.हरकुळ बु. ता.कणकवली .जि.सिंधुदुर्ग पिन. ४१६६०२')
                            window.update()
                            assistantt_speaks('दूरध्वनी')
                            assistantt_speaks('02367-233812')
                            var.set('02367-233812')
                            window.update()
                        elif 'होमिओपॅथी' in str(tet):
                            assistantt_speaks('विद्यापीठाच्या नाव')
                            assistantt_speaks('होमिओपॅथी वैद्यकीय महाविद्यालय.')
                            var.set('होमिओपॅथी वैद्यकीय महाविद्यालय.')
                            window.update()
                            assistantt_speaks('विद्यापीठाच्या पत्ता')
                            assistantt_speaks('मुख्य वेंगुर्ले रस्ता , मु.पो.ता.वेंगुर्ले , जि.सिंधुदुर्ग .पिन ४१६५१६')
                            var.set('मुख्य वेंगुर्ले रस्ता , मु.पो.ता.वेंगुर्ले , जि.सिंधुदुर्ग .पिन ४१६५१६')
                            window.update()
                            assistantt_speaks('दूरध्वनी')
                            assistantt_speaks(' 02366-262165')
                            var.set(' 02366-262165')
                            window.update()

                        elif 'None' in str(tet):
                            get_audios()

                    elif 'विद्यापीठ' in str(te):
                        assistantt_speaks('तुम्हाला कोणत्या विद्यापीठाच्या जाणून घ्यायचे आहे?')
                        assistantt_speaks('एम .आय.टी.एम. अभियांत्रिकी महाविद्यालय .')
                        var.set('एम .आय.टी.एम. अभियांत्रिकी महाविद्यालय .')
                        window.update()
                        assistantt_speaks('एस.एस.पी.एम. मेडिकल कॉलेज')
                        var.set('एस.एस.पी.एम. मेडिकल कॉलेज')
                        window.update()
                        assistantt_speaks('डी. एड व बी. एड. महाविद्यालय ४ + १')
                        var.set('डी. एड व बी. एड. महाविद्यालय ४ + १')
                        window.update()
                        assistantt_speaks('तंत्र निकेतन महाविद्यालय मालवण')
                        var.set('तंत्र निकेतन महाविद्यालय मालवण')
                        window.update()
                        assistantt_speaks('भाई साहेब सावंत आयुर्वेदिक महाविद्यालय')
                        var.set('भाई साहेब सावंत आयुर्वेदिक महाविद्यालय')
                        window.update()
                        assistantt_speaks('महाविद्यालय २१ , कनिष्ठ महाविद्यालय ४३')
                        var.set('महाविद्यालय २१ , कनिष्ठ महाविद्यालय ४३')
                        window.update()
                        assistantt_speaks('शासकीय औद्योगिक प्रशिक्षण संस्था .')
                        var.set('शासकीय औद्योगिक प्रशिक्षण संस्था .')
                        window.update()
                        assistantt_speaks('सिंधुदुर्ग शिक्षण प्रसारक , अभियांत्रिकी महाविद्यालय')
                        var.set('सिंधुदुर्ग शिक्षण प्रसारक , अभियांत्रिकी महाविद्यालय')
                        window.update()
                        assistantt_speaks('होमिओपॅथी वैद्यकीय महाविद्यालय.')
                        var.set('होमिओपॅथी वैद्यकीय महाविद्यालय.')
                        window.update()
                        tet = get_audios()
                        if 'एम आय टी एम ' in str(tet): #अभियांत्रिकी
                            assistantt_speaks('विद्यापीठाच्या नाव')
                            assistantt_speaks('एम .आय.टी.एम. अभियांत्रिकी महाविद्यालय .')
                            var.set('एम .आय.टी.एम. अभियांत्रिकी महाविद्यालय .')
                            window.update()
                            assistantt_speaks('विद्यापीठाच्या पत्ता')
                            assistantt_speaks('सुकळवाड , ओरोस रेल्वे स्थानक जवळ , ता. मालवण .जि.सिंधुदुर्ग .पिन. ४१६५३४')
                            var.set('सुकळवाड , ओरोस रेल्वे स्थानक जवळ , ता. मालवण .जि.सिंधुदुर्ग .पिन. ४१६५३४')
                            window.update()
                            assistantt_speaks('दूरध्वनी ')
                            assistantt_speaks('02362-228551')
                            var.set('02362-228551')
                            window.update()

                        elif 'मेडिकल' in str(tet):
                            assistantt_speaks('विद्यापीठाच्या नाव')
                            assistantt_speaks('एस.एस.पी.एम. मेडिकल कॉलेज')
                            var.set('एस.एस.पी.एम. मेडिकल कॉलेज')
                            window.update()
                            assistantt_speaks('विद्यापीठाच्या पत्ता')
                            assistantt_speaks('पडवे . मालवण -कसाल रोड , रानबाम्बुली , ता.कुडाळ .जि. सिंधुदुर्ग .')
                            var.set('पडवे . मालवण -कसाल रोड , रानबाम्बुली , ता.कुडाळ .जि. सिंधुदुर्ग .')
                            window.update()
                            assistantt_speaks('दूरध्वनी')
                            assistantt_speaks('02367-234000')
                            var.set('02367-234000')
                            window.update()

                        elif 'बी एड' in str(tet):
                            assistantt_speaks('विद्यापीठाच्या नाव')
                            assistantt_speaks('डी. एड व बी. एड. महाविद्यालय ४ + १')
                            var.set('डी. एड व बी. एड. महाविद्यालय ४ + १')
                            window.update()
                            assistantt_speaks('विद्यापीठाच्या पत्ता')
                            assistantt_speaks('सिंधुदुर्ग जिल्हा')
                            var.set('सिंधुदुर्ग जिल्हा')
                            window.update()
                        elif 'तंत्र निकेतन ' in str(tet): #महाविद्यालय
                            assistantt_speaks('विद्यापीठाच्या नाव')
                            assistantt_speaks('तंत्र निकेतन महाविद्यालय मालवण')
                            var.set('तंत्र निकेतन महाविद्यालय मालवण')
                            window.update()
                            assistantt_speaks('विद्यापीठाच्या पत्ता')
                            assistantt_speaks('मु.पो.कुंभारमाठ . ता.मालवण . जिल्हा .सिंधुदुर्ग . पिन .४१६६०६')
                            var.set('मु.पो.कुंभारमाठ . ता.मालवण . जिल्हा .सिंधुदुर्ग . पिन .४१६६०६')
                            window.update()
                            assistantt_speaks('दूरध्वनी')
                            assistantt_speaks(' 02365-252223')
                            var.set(' 02365-252223')
                            window.update()
                        elif 'आयुर्वेदिक ' in str(tet):
                            assistantt_speaks('विद्यापीठाच्या नाव')
                            assistantt_speaks('भाई साहेब सावंत आयुर्वेदिक महाविद्यालय')
                            var.set('भाई साहेब सावंत आयुर्वेदिक महाविद्यालय')
                            window.update()
                            assistantt_speaks('विद्यापीठाच्या पत्ता')
                            assistantt_speaks('मुंबई-गोवा रस्ता , खासकीलवाडा ,मु.पो.ता.सावंतवाडी जि.सिंधुदुर्ग .पिन.४१६५१० .')
                            var.set('मुंबई-गोवा रस्ता , खासकीलवाडा ,मु.पो.ता.सावंतवाडी जि.सिंधुदुर्ग .पिन.४१६५१० .')
                            window.update()
                            assistantt_speaks('दूरध्वनी')
                            assistantt_speaks('02363-272302')
                            var.set('02363-272302')
                            window.update()
                        elif 'महाविद्यालय' in str(tet):
                            assistantt_speaks('विद्यापीठाच्या नाव')
                            assistantt_speaks('महाविद्यालय २१ , कनिष्ठ महाविद्यालय ४३')
                            var.set('महाविद्यालय २१ , कनिष्ठ महाविद्यालय ४३')
                            window.update()
                            assistantt_speaks('विद्यापीठाच्या पत्ता')
                            assistantt_speaks('सिंधुदुर्ग जिल्हा')
                            var.set('सिंधुदुर्ग जिल्हा')
                            window.update()
                            
                        elif 'शासकीय  ' in str(tet): #औद्योगिक प्रशिक्षण
                            assistantt_speaks('विद्यापीठाच्या नाव')
                            assistantt_speaks('शासकीय औद्योगिक प्रशिक्षण संस्था .')
                            var.set('शासकीय औद्योगिक प्रशिक्षण संस्था .')
                            window.update()
                            assistantt_speaks('विद्यापीठाच्या पत्ता')
                            assistantt_speaks('मु.पो.ओरोस . सिंधुदुर्गनगरी ता.कुडाळ . जिल्हा सिंधुदुर्ग . पिन .४१६८१२')
                            var.set('मु.पो.ओरोस . सिंधुदुर्गनगरी ता.कुडाळ . जिल्हा सिंधुदुर्ग . पिन .४१६८१२')
                            window.update()
                            assistantt_speaks('दूरध्वनी')
                            assistantt_speaks('02362-228090')
                            var.set('02362-228090')
                            window.update()
                        elif 'अभियांत्रिकी' in str(tet):
                            assistantt_speaks('विद्यापीठाच्या नाव')
                            assistantt_speaks('सिंधुदुर्ग शिक्षण प्रसारक , अभियांत्रिकी महाविद्यालय')
                            var.set('सिंधुदुर्ग शिक्षण प्रसारक , अभियांत्रिकी महाविद्यालय')
                            window.update()
                            assistantt_speaks('विद्यापीठाच्या पत्ता')
                            assistantt_speaks('पो.हरकुळ बु. ता.कणकवली .जि.सिंधुदुर्ग पिन. ४१६६०२')
                            var.set('पो.हरकुळ बु. ता.कणकवली .जि.सिंधुदुर्ग पिन. ४१६६०२')
                            window.update()
                            assistantt_speaks('दूरध्वनी')
                            assistantt_speaks('02367-233812')
                            var.set('02367-233812')
                            window.update()
                        elif 'होमिओपॅथी' in str(tet):
                            assistantt_speaks('विद्यापीठाच्या नाव')
                            assistantt_speaks('होमिओपॅथी वैद्यकीय महाविद्यालय.')
                            var.set('होमिओपॅथी वैद्यकीय महाविद्यालय.')
                            window.update()
                            assistantt_speaks('विद्यापीठाच्या पत्ता')
                            assistantt_speaks('मुख्य वेंगुर्ले रस्ता , मु.पो.ता.वेंगुर्ले , जि.सिंधुदुर्ग .पिन ४१६५१६')
                            var.set('मुख्य वेंगुर्ले रस्ता , मु.पो.ता.वेंगुर्ले , जि.सिंधुदुर्ग .पिन ४१६५१६')
                            window.update()
                            assistantt_speaks('दूरध्वनी')
                            assistantt_speaks(' 02366-262165')
                            var.set(' 02366-262165')
                            window.update()

                        elif 'None' in str(tet):
                            get_audios()

                    elif 'वीज' in str(te):
                        assistantt_speaks('वीज कार्यालय')
                        assistantt_speaks('एम.एस.ई.बी . सिंधुदुर्गनगरी')
                        var.set('एम.एस.ई.बी . सिंधुदुर्गनगरी')
                        window.update()
                        assistantt_speaks('पत्ता')
                        assistantt_speaks('ओरोस पोळीचे स्टेशन जवळ , मु.पो.ओरोस ,ता. कुडाळ . जि.सिंधुदुर्ग .पिन .४१६८१२')
                        var.set('ओरोस पोळीचे स्टेशन जवळ , मु.पो.ओरोस ,ता. कुडाळ . जि.सिंधुदुर्ग .पिन .४१६८१२')
                        window.update()
                        assistantt_speaks('दूरध्वनी')
                        assistantt_speaks('02362-228767')
                        var.set('02362-228767')
                        window.update()
                    elif 'रुग्णालये' in str(te):
                        assistantt_speaks('रुग्णालयाचे नाव')
                        assistantt_speaks('जिल्हा रुग्णालय सिंधुदुर्ग')
                        var.set('जिल्हा रुग्णालय सिंधुदुर्ग')
                        window.update()
                        assistantt_speaks('रुग्णालयाचा पत्ता')
                        assistantt_speaks('मु.पो.ओरोस . ता.कुडाळ . जि. सिंधुदुर्ग .पिन. ४१६८१२ ')
                        var.set('मु.पो.ओरोस . ता.कुडाळ . जि. सिंधुदुर्ग .पिन. ४१६८१२ ')
                        window.update()
                        assistantt_speaks('दूरध्वनी क्र.')
                        assistantt_speaks('०२३६२- २२८९०१ ')
                        var.set('०२३६२- २२८९०१')
                        window.update()
                        assistantt_speaks(' किंवा ')
                        assistantt_speaks('०२३६२-२२८९०२')
                        var.set('०२३६२-२२८९०२')
                        window.update()

                    elif 'नगरपालिका' in str(te):
                        assistantt_speaks('तुम्हाला कोणत्या नगरपालिकेची माहिती हवी आहे?')
                        assistantt_speaks('कणकवली')
                        var.set('कणकवली')
                        window.update()
                        assistantt_speaks('कसई – दोडामार्ग')
                        var.set('कसई – दोडामार्ग')
                        window.update()
                        assistantt_speaks('कुडाळ')
                        var.set('कुडाळ')
                        window.update()
                        assistantt_speaks('देवगड – जामसंडे')
                        var.set('देवगड – जामसंडे')
                        window.update()
                        assistantt_speaks('मालवण')
                        var.set('मालवण')
                        window.update()
                        assistantt_speaks('वाभवे – वैभववाडी')
                        var.set('वाभवे – वैभववाडी')
                        window.update()
                        tetx = get_audios()
                        
                        if 'कणकवली' in str(tetx):
                            assistantt_speaks('नगरपालिकेच्या पत्ता')
                            assistantt_speaks('मु.पो.ता.कणकवली .जि -सिंधुदुर्ग .पिन . ४१६६०२')
                            var.set('मु.पो.ता.कणकवली .जि -सिंधुदुर्ग .पिन . ४१६६०२')
                            window.update()
                            assistantt_speaks('ईमेल')
                            assistantt_speaks(' kankavalinp[at]gmail[dot]com')
                            var.set(' kankavalinp[at]gmail[dot]com')
                            window.update()
                            assistantt_speaks('दूरध्वनी')
                            assistantt_speaks('02367-232007')
                            var.set(': 02367-232007')
                            window.update()
                        elif 'कसई' in str(tetx):
                            assistantt_speaks('नगरपालिकेच्या पत्ता')
                            assistantt_speaks('मु.पो. दोडामार्ग ता .दोडामार्ग . जिल्हा. सिंधुदुर्ग. पिन.४१६५१२')
                            var.set('मु.पो. दोडामार्ग ता .दोडामार्ग . जिल्हा. सिंधुदुर्ग. पिन.४१६५१२')
                            window.update()
                            assistantt_speaks('ईमेल')
                            assistantt_speaks(' npkasidodamarg[at]gmail[dot]com')
                            var.set(' npkasidodamarg[at]gmail[dot]com')
                            window.update()
                            assistantt_speaks('दूरध्वनी')
                            assistantt_speaks(' 02363-256633')
                            var.set(' 02363-256633')
                            window.update()
                        elif 'कुडाळ' in str(tetx):
                            assistantt_speaks('नगरपालिकेच्या पत्ता')
                            assistantt_speaks('मु.पो.ता. कुडाळ .जि. सिंधुदुर्ग .पिन .४१६५२८')
                            var.set('मु.पो.ता. कुडाळ .जि. सिंधुदुर्ग .पिन .४१६५२८')
                            window.update()
                            assistantt_speaks('ईमेल')
                            assistantt_speaks('kudalnagarpanchayat[at]gmail[dot]com')
                            var.set('kudalnagarpanchayat[at]gmail[dot]com')
                            window.update()
                        elif 'देवगड' in str(tetx):
                            assistantt_speaks('नगरपालिकेच्या पत्ता')
                            assistantt_speaks('मु.पो.ता.देवगड . जि . सिंधुदुर्ग .पिन . ४१६६१२')
                            var.set('मु.पो.ता.देवगड . जि . सिंधुदुर्ग .पिन . ४१६६१२')
                            window.update()
                            assistantt_speaks('ईमेल')
                            assistantt_speaks('devgadjamsandenp[at]gmail[dot]com')
                            var.set('devgadjamsandenp[at]gmail[dot]com')
                            window.update()
                                                    
                        elif 'मालवण ' in str(tetx):
                            assistantt_speaks('नगरपालिकेच्या पत्ता')
                            assistantt_speaks('मु.पो.ता.मालवण. जि.सिंधुदुर्ग .पिन. ४१६६०६')
                            var.set('मु.पो.ता.मालवण. जि.सिंधुदुर्ग .पिन. ४१६६०६')
                            window.update()
                            assistantt_speaks('ईमेल')
                            assistantt_speaks('comalvan[at]gmail[dot]com')
                            var.set('comalvan[at]gmail[dot]com')
                            window.update()
                            
                            
                        elif 'वाभवे' in str(tetx):
                            assistantt_speaks('नगरपालिकेच्या पत्ता')
                            assistantt_speaks('मु.पो.ता. वैभववाडी . जि.सिंधुदुर्ग .पिन -४१६८१०')
                            var.set('मु.पो.ता. वैभववाडी . जि.सिंधुदुर्ग .पिन -४१६८१०')
                            window.update()
                            assistantt_speaks('ईमेल')
                            assistantt_speaks('npvabhavevaibhvwadi[at]gmail[dot]com')
                            var.set('npvabhavevaibhvwadi[at]gmail[dot]com')
                            window.update()

                        elif 'None' in str(tetx):
                            get_audios()

                    elif 'अ शासकीय संस्था' in str(te):
                        assistantt_speaks('दोन अ शासकीय संस्था आहे  ')
                        assistantt_speaks('पहिला ')
                        assistantt_speaks('अजिंक्य अदवेंचर आणि आपत्कालीन मदत संस्था')
                        var.set('अजिंक्य अदवेंचर आणि आपत्कालीन मदत संस्था')
                        window.update()
                        assistantt_speaks('संस्थांच्या पत्ता')
                        assistantt_speaks('एपी. ता. सावंतवाडी जिल्हा सिंधुदुर्ग मु .पो. सावंतवाडी . जि .सिंधुदुर्ग .')
                        var.set('एपी. ता. सावंतवाडी जिल्हा सिंधुदुर्ग मु .पो. सावंतवाडी . जि .सिंधुदुर्ग .')
                        window.update()
                        assistantt_speaks('दूरध्वनी')
                        assistantt_speaks(' 9422434265')
                        var.set(' 9422434265')
                        window.update()
                        assistantt_speaks('दुसरा')
                        assistantt_speaks('महाराष्ट्र आपत्ती व्यवस्थापन व शैक्षणिक प्रशिक्षण संस्था')
                        var.set('महाराष्ट्र आपत्ती व्यवस्थापन व शैक्षणिक प्रशिक्षण संस्था')
                        window.update()
                        assistantt_speaks('संस्थांच्या पत्ता')
                        assistantt_speaks('मु .पो . माळेवाड . कोंडुरा . ता . सावंतवाडी .जि .सिंधुदुर्ग .')
                        var.set('मु .पो . माळेवाड . कोंडुरा . ता . सावंतवाडी .जि .सिंधुदुर्ग .')
                        window.update()
                        assistantt_speaks('दूरध्वनी')
                        assistantt_speaks('7767989888')
                        var.set('7767989888')
                        window.update()

                    elif 'टपाल' in str(te):
                        assistantt_speaks('टपाल मुख्यालय सिंधुदुर्गनगरी')
                        assistantt_speaks('पत्ता ')
                        assistantt_speaks('बी.एस.एन .एल . सिंधुदुर्ग जवळ , सिंधुदुर्गनगरी')
                        var.set('बी.एस.एन .एल . सिंधुदुर्ग जवळ , सिंधुदुर्गनगरी')
                        window.update()
                        assistantt_speaks('बँकेची वेबसाइट उघडली आहे')
                        webbrowser.open('https://www.corpbank.com/')

                    elif 'शाळा' in str(te):
                        assistantt_speaks('शाळेचा नाव')
                        assistantt_speaks('जि.प.प्राथमिक शाळा ओरोस')
                        var.set('जि.प.प्राथमिक शाळा ओरोस')
                        window.update()
                        assistantt_speaks('शाळेचा पत्ता')
                        assistantt_speaks('मु .पो.ओरोस .सिंधुदुर्गनगरी ता . कुडाळ .जि .सिंधुदुर्ग . पिन. ४१६८१२')
                        var.set('मु .पो.ओरोस .सिंधुदुर्गनगरी ता . कुडाळ .जि .सिंधुदुर्ग . पिन. ४१६८१२')
                        window.udate()
                        assistantt_speaks('शाळेचा नाव')
                        assistantt_speaks('प्राथमिक शाळा १४२१ , खासगी ४२')
                        var.set('प्राथमिक शाळा १४२१ , खासगी ४२')
                        window.update()
                        assistantt_speaks('शाळेचा पत्ता')
                        assistantt_speaks('शिक्षण विभाग प्राथमिक , जि . प. सिंधुदुर्ग . सिंधुदुर्गनगरी , पो. ओरोस , ता.कुडाळ .जि .सिंधुदुर्ग .पिन - ४१६८१२ .')
                        var.set('शिक्षण विभाग प्राथमिक , जि . प. सिंधुदुर्ग . सिंधुदुर्गनगरी , पो. ओरोस , ता.कुडाळ .जि .सिंधुदुर्ग .पिन - ४१६८१२ .')
                        window.update()
                        assistantt_speaks('शाळेचा नाव')
                        assistantt_speaks('हायस्कूल १८६ , भारत सरकार १ , विना अनुदानित २२')
                        var.set('हायस्कूल १८६ , भारत सरकार १ , विना अनुदानित २२')
                        window.update()
                        assistantt_speaks('शाळेचा पत्ता')
                        assistantt_speaks('शिक्षण विभाग माध्यमिक , जि . प. सिंधुदुर्ग . सिंधुदुर्गनगरी , पो. ओरोस , ता.कुडाळ .जि .सिंधुदुर्ग .पिन - ४१६८१२ .')
                        var.set('शिक्षण विभाग माध्यमिक , जि . प. सिंधुदुर्ग . सिंधुदुर्गनगरी , पो. ओरोस , ता.कुडाळ .जि .सिंधुदुर्ग .पिन - ४१६८१२ .')
                        window.update()

                    elif 'None' in str(te):
                        get_audios()
                elif 'None' in str(t):
                    get_audios()


            elif 'पर्यटन' in str(text):
                assistantt_speaks('सिंधुदुर्ग कसे पोहोचायचे')
                var.set('सिंधुदुर्ग कसे पोहोचायचे')
                window.update()
                assistantt_speaks('पर्यटन स्थळे')
                var.set('पर्यटन स्थळे')
                window.update()
                assistantt_speaks('संस्कृती आणि वारसा')
                var.set('संस्कृती आणि वारसा')
                window.update()
                assistantt_speaks('साहसी क्रियाकलाप')
                var.set('साहसी क्रियाकलाप')
                window.update()
                assistantt_speaks('कोणत्या विषयावर आपल्याला अधिक माहिती हवी आहे?')
                speak = get_audios()
                 
                if 'सिंधुदुर्ग कसा पोहोचायचा' in str(speak):
                    assistantt_speaks('सिंधुदुर्ग पोहोचणे साठी ')
                    assistantt_speaks('आम्ही महामार्ग घेऊ शकतो किंवा लोहमार्ग घेऊ शकतो किंवा हवाई मार्ग घेऊ शकतो')
                    assistantt_speaks('महामार्ग घेऊन आम्ही सिंधुदुर्ग येथे पोहोचण्यासाठी मुंबई-गोवा  महामार्ग क्र.१७ ने प्रवास करू शकता .जो कणकवली , कुडाळ व सावंतवाडी या तीन मुख्य शहरातून जोडलेला आहे')
                    assistantt_speaks('लोहमार्ग घेऊन आम्ही सिंधुदुर्ग येथे पोहोचण्यासाठी आपण कोकणरेल्वे लोहमार्ग वापरून मुख्य रेल्वेस्थानक कणकवली,सिंधुदुर्ग ,कुडाळ व सावंतवाडी यापैकी कोणतेही स्थानक वापरून प्रवास करू शकतो. सिंधुदुर्ग जिल्हा मुख्यालय सिंधुदुर्ग रेल्वे स्थानकापासून ४-५ कि.मी. अंतरावर आहे .')
                    assistantt_speaks('हवाई मार्ग घेऊन आम्ही सिंधुदुर्ग येथे पोहोचण्यासाठी हवाई मार्गाचा वापर करून रत्नागिरी,गोवा किवा बेळगाव येथून विमानप्रवास करू शकतो. जिल्हा मुख्यालय ते तीनही विमानतळ साधारण १०० कि.मी.वर आहेत .')

                elif 'संस्कृती आणि वारसा' in str(speak):
                    assistantt_speaks('संस्कृती आणि वारसा यात दोन समावेश आहे')
                    assistantt_speaks('पहिला')
                    assistantt_speaks('वैशिष्टपूर्ण ग्रामीण जीवन')
                    var.set('वैशिष्टपूर्ण ग्रामीण जीवन')
                    window.update()
                    assistantt_speaks('सिंधुदुर्ग जिल्हा येथे वैशिष्टपूर्ण ग्रामीण जीवन अनुभवता येते. मुख्य रोजगार शेती असल्यामुळे हिरवीगार भात शेती पावसाळ्यात अनुभवता येते. ')
                    assistantt_speaks('घरे सामान्यता जांभा दगड वापरून बांधलेली व कौलारू आहेत. पर्जन्यमान सरासरी जास्त असल्यामुळे उतरती कौलारू घरे सापडतात.')
                    assistantt_speaks('जोडधंदा पशुपालन व किनारी प्रदेशात मत्स्य व्यवसायावर आधारित जीवन बघायला मिळते')
                    assistantt_speaks('जिल्ह्यातील बहुतांश भाग हा दाट वर्षावनाने झाकला गेलेला आहे')
                    assistantt_speaks('जंगली मांजरे या रानटी प्राण्यांसाठी तसेच ससे,रानटी कोंबड्या व रानटी रेडे यांच्यासाठी उपयुक्त निवासस्थान आहे')
                    assistantt_speaks('जंगली रेडे कोल्हापूर जिल्ह्यातील राधानगरी अभयारण्यातून अन्न पाण्याच्या शोधात येथे येतात')
                    assistantt_speaks('अलीकडेच कर्नाटकातील खानापूर जंगलातून सिंधुदुर्ग जिल्ह्यातील दोडामार्ग तालुक्यात हत्तींचा प्रवेश झाला आहे')
                    assistantt_speaks('इथे प्रथमच वस्त्तीच्या शोधात हत्तींनी प्रवेश केला.तिलारी येथील प्रमुख पाठबंधारे प्रकल्प हा घनदाट वर्षावनांचा प्रदेश असून हत्तींसाठी एक महत्वाचे स्थान बनले आहे')
                    assistantt_speaks('परंतु येथील स्थानिक लोकांना हत्तींमुळे झालेली पिंकाची नासधूस व वृक्षतोड यांचा सामना करावा लागत आहे.')
                    assistantt_speaks('दुसरा')
                    assistantt_speaks('लाकडी खेळणी')
                    var.set('लाकडी खेळणी')
                    window.update()
                    assistantt_speaks('सावंतवाडी येथे लाकडी खेळणी बनविण्याच्या व्यवसायाला राजाश्रय मिळाला आहे')
                    assistantt_speaks('तसेच हि कला करणारे कारागीर गोवा व कारवार येथून सावंतवाडी येथे वसलेले आहेत')
                    assistantt_speaks('या लोकसमुहास चित्तार असे संबोधतात . रंगीबेरंगी लाकडी खेळणी दिसायलाही हुबेहूब असतात')
                    assistantt_speaks('सावंतवाडी या  शहरातून जाणारा राष्ट्रीय महामार्ग क्र.१७ तसेच कणकवली, सिंधुदुर्गनगरी, कुडाळ, सावंतवाडी येथील रेल्वे स्थानकांवरून येथे पोचता येते.')

                elif 'साहसी' in str(speak):
                    assistantt_speaks('या जिल्ह्यात एक साहसी क्रियाकलाप आहे')
                    assistantt_speaks('स्कूबा डायविंग')
                    var.set('स्कूबा डायविंग')
                    window.update()
                    assistantt_speaks('स्कूबा डायविंग हा साहसी प्रकार सिंधुदुर्ग जिल्हा येथे मालवण बीच , तारकर्ली बीच याठिकाणी उपलब्ध आहे. समुद्राखालील निसर्ग सौंदर्य ,जैवविविधता आपणास या प्रकारामुळे अनुभवता येईल . या साहसी प्रकारात ऑक्सिजन सिलिंडर घेऊन आपणास समुद्राखालील जग पाहता येईल. त्यापूर्वी प्रशिक्षक आपणास योग्य ते मार्गदर्शन करतात .')

                elif 'पर्यटन स्थळे' in str(speak):
                    assistantt_speaks('सिंधुदुर्गात तीन पर्यटन स्थळे आहेत')
                    assistantt_speaks('सावंतवाडी राजवाडा')
                    var.set('सावंतवाडी राजवाडा')
                    window.update()
                    assistantt_speaks('आंबोली')
                    var.set('आंबोली')
                    window.update()
                    assistantt_speaks('सिंधुदुर्ग जलदुर्ग')
                    var.set('सिंधुदुर्ग जलदुर्ग')
                    window.update()
                    assistantt_speaks('आपल्याला कोणाविषयी माहिती हवी आहे?')
                    speaks = get_audios()

                    if 'सावंतवाडी राजवाडा' in str(speaks):
                        var.set('सावंतवाडी राजवाडा')
                        window.update()
                        assistantt_speaks('सावंतवाडी राजवाडा सिंधुदुर्गातील एक महत्वाचे पर्यटन स्थळ ओळखले जाते. राजवाड्याची बांधणी खेम सावंत भोसले संस्थानांनी १७५५-१८०३ या काळात केली. सावंतवाडी शहरातील हे सुंदर पर्यटन स्थळ असून मुंबई,पुणे, तसेच कोल्हापूर येथून महामार्गाने येथे पोहोचता येते .')
                        webbrowser.open('https://sindhudurg.nic.in/gallery/%e0%a4%b8%e0%a4%be%e0%a4%b5%e0%a4%82%e0%a4%a4%e0%a4%b5%e0%a4%be%e0%a4%a1%e0%a5%80_%e0%a4%b0%e0%a4%be%e0%a4%9c%e0%a4%b5%e0%a4%be%e0%a4%a1%e0%a4%be/')
                        assistantt_speaks('सावंतवाडी राजवाडा ची चित्रे बघु शकता')
                        webbrowser.open('https://www.google.com/maps/dir//sawantwadi+palace+sindhudurg/@17.4969708,72.4981754,8z/data=!4m8!4m7!1m0!1m5!1m1!1s0x3bbff55b8c40c125:0xf7c05ea8ef31fc66!2m2!1d73.8248215!2d15.9067516')

                    elif 'आंबोली' in str(speaks):
                        var.set('आंबोली')
                        window.update()
                        assistantt_speaks('आंबोली  ता.सावंतवाडी  , जि. सिंधुदुर्ग .आंबोली  जाण्यासाठी सावंतवाडी येथून बसेस उपलब्ध आहेत.  सावंतवाडी , मुंबई ,पुणे व कोल्हापूर येथून महामार्गाने जोडलेले आहेत. आंबोली हे पावसाळ्यातील खास प्रेक्षणीय स्थळ आहे. येथील धबधबे व जैवविविधता खूपच रमणीय आहे. लगतचा जिल्हा कोल्हापूर तसेच बेळगाव येथून पर्यटक पावसाळ्यात मोठ्या संख्येने येतात.')
                        webbrowser.open('https://sindhudurg.nic.in/gallery/%e0%a4%86%e0%a4%82%e0%a4%ac%e0%a5%8b%e0%a4%b2%e0%a5%80-%e0%a4%a5%e0%a4%82%e0%a4%a1-%e0%a4%b9%e0%a4%b5%e0%a5%87%e0%a4%9a%e0%a5%87-%e0%a4%a0%e0%a4%bf%e0%a4%95%e0%a4%be%e0%a4%a3/')
                        assistantt_speaks('आंबोली चे चित्रे बघु शकता')

                    elif 'सिंधुदुर्ग जलदुर्ग' in str(speaks):
                        var.set('सिंधुदुर्ग जलदुर्ग')
                        window.update()
                        assistantt_speaks('सिंधुदुर्ग जलदुर्ग हा अरबी समुद्रात बांधलेला असून बहुचर्चित पर्यटन स्थळ आहे . मालवण शहरातील समुद्रात कुरटे बेटावर हा किल्ला शिवकालीन इतिहासाची साक्ष देतो .मुंबईपासून सुमारे ४५० कि.मी.अंतरावर हे पर्यटन क्षेत्र आहे .')
                        webbrowser.open('https://sindhudurg.nic.in/gallery/%e0%a4%b8%e0%a4%bf%e0%a4%82%e0%a4%a7%e0%a5%81%e0%a4%a6%e0%a5%81%e0%a4%b0%e0%a5%8d%e0%a4%97-%e0%a4%9c%e0%a4%b2%e0%a4%a6%e0%a5%81%e0%a4%b0%e0%a5%8d%e0%a4%97/')
                        assistantt_speaks('सिंधुदुर्ग जलदुर्ग चे चित्रे बघु शकता')
                        webbrowser.open('https://www.google.com/maps/dir//sindhudurg+jaldurg/@17.5647907,72.447111,8z/data=!4m8!4m7!1m0!1m5!1m1!1s0x3beaa82170000001:0xd9f190e26c66ce46!2m2!1d73.459744!2d16.0427965')


                    elif 'None' in str(speaks):
                        get_audios()

            elif 'सूचना' in str(text):
                
                webbrowser.open('file:///C:/Users/Jaimini%20Studios/Desktop/JARVIS/.vscode/form.html')
                sys.exit()
                
            
                

            elif 'None' in str(text):
                get_audios()               
def update(ind):
    frame = frames[(ind)%50]
    #framee = frame1[[ind)%100]]
    ind += 1
    label.configure(image=frame)
    window.after(100, update, ind)

label2 = Label(window, textvariable = var1, bg = '#FAB60C',)
label2.config(font=("Courier", 20),)
var1.set('नमस्कार')
label2.pack()


label1 = Label(window, textvariable = var, bg = '#ADD8E6')
label1.config(font=("Courier", 20))
var.set('मदतीसाठी बटण दाबा')
label1.pack()

frames = [PhotoImage(file='C:\\Users\\Jaimini Studios\\Desktop\\JARVIS\\.vscode\\Jarvis-master\\Assistant.gif',format = 'gif -index %i' %(i)) for i in range(100)]
window.title('APPLICATION')


label = Label(window, width = 350, height = 400)
label.pack()
window.after(0, update, 0)

photo = [PhotoImage(file="C:\\Users\\Jaimini Studios\\Desktop\\JARVIS\\.vscode\\micnew.gif")]
#photo = photos.resize(300,400)
btn2 = Button(image = photo, command = marplay,)
#btn2.config(width = 50, height = 50)
btn2.pack()

window.mainloop()